---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks:
    - name: Get datacenters
      community.vmware.vmware_datacenter_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
        validate_certs: false
      register: datacenter_info

    - name: Print vCenter server information
      debug:
        var: datacenter_info
