## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_deploy_ovf_module.html
- hosts: localhost
  vars_files: ./vars.yaml

  tasks:
    - community.vmware.vmware_deploy_ovf:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
        validate_certs: false
        datastore: "{{ datastore_name }}"
        name: "{{ item.vmname }}"
        networks: "{{ item.networks }}"
        power_on: false
        ovf: "/vmfs/volumes/661ce08d-87480024-537c-d89d67eea260/OVF/Linux%20Templates.ovf"
        disk_provisioning: thin
      loop:
        - { networks: "{u'Network adapter 1':u'K8S Dev'}", vmname: "Worker-Node-01" }
        - { networks: "{u'Network adapter 1':u'K8S Dev'}", vmname: "Worker-Node-02" }
        - { networks: "{u'Network adapter 1':u'K8S Dev'}", vmname: "Worker-Node-03" }
        - { networks: "{u'Network adapter 1':u'K8S Dev'}", vmname: "Master-Node" }
        - { networks: "{u'Network adapter 1':u'K8S Dev'}", vmname: "Worker-Node-04" }
        - { networks: "{u'Network adapter 1':u'Monitoring'}", vmname: "Monitoring" }
        - { networks: "{u'Network adapter 1':u'CI/CD Dev'}", vmname: "Jenkins" }
        - { networks: "{u'Network adapter 1':u'CI/CD Dev'}", vmname: "Argo" }
        - { networks: "{u'Network adapter 1':u'DB Dev'}", vmname: "DB-Dev" }
        - { networks: "{u'Network adapter 1':u'DB Dev'}", vmname: "Redis for Dev" }
      delegate_to: localhost
