## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_export_ovf_module.html
- hosts: localhost
  vars_files: ./vars.yaml

  tasks:
    - community.vmware.vmware_export_ovf:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
        name: "LinuxTemplates"
        validate_certs: false
        export_with_images: true
        export_dir: "{{datastore_path}}/OVF/"
      delegate_to: localhost
