AWSTemplateFormatVersion: '2010-09-09'
Description: Network For dev

# Metadata:

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.
  VPCCidrBlock:
    Type: String
    AllowedPattern: (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/16

# Mappings:

# Conditions

# Transform

Resources:
  # VPC作成
  akaneVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub
          - ${ProjectName}-${EnvType}
          - {SystemName: !Ref ProjectName, EnvType: !Ref EnvType}
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  akaneVPC:
    Value: !Ref CreateVPC
    Export:
      Name: !Sub
        - ${ProjectName}-${EnvType}-vpc
        - {SystemName: !Ref ProjectName, EnvType: !Ref EnvType}
