---
- name: Loop register test
  gather_facts: no
  hosts: seoul

  tasks:
    - name: Looping echo tesk
      shell: "echo This is my item: {{ item }}"
      loop:
        - one
        - two
      register: echo_results

    - name: Show echo_results variable
      debug:
        var: echo_results
