---
- name: Enable web services
  hosts: seoul
  become: yes
  tasks:
    - name: httpd and firewalld installed
      yum:
        name:
          - httpd
          - firewalld
        state: latest

    - name: html page is installed
      copy:
        content: "Welcome to web server"
        dest: /var/www/html/index.html

    - name: firewalld enable and running
      service:
        name: firewalld
        enabled: yes
        state: started

- name: Allow firewall rule for webserver
  hosts: seoul
  become: yes
  tasks:
    - name: firewalld permits access to httpd service
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: yes
        state: started

